{{ if $.Values.ingressroute.enabled -}}

---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "process-exporter-{{$.Values.EnvName}}-basicauth"
  namespace: "{{$.Values.Namespace}}"
type: "Opaque"
data:
  users: "{{ htpasswd $.Values.ingressroute.basicauth.user $.Values.ingressroute.basicauth.pass | b64enc }}"

---
apiVersion: "traefik.io/v1alpha1"
kind: "Middleware"
metadata:
  name: "process-exporter-{{$.Values.EnvName}}-basicauth"
  namespace: "{{$.Release.Namespace}}"
spec:
  basicAuth:
    secret: "process-exporter-{{$.Values.EnvName}}-basicauth"

---
apiVersion: "traefik.io/v1alpha1"
kind: "IngressRoute"
metadata:
  name: "process-exporter-{{$.Values.EnvName}}"
  namespace: "{{$.Release.Namespace}}"
spec:
  entryPoints:
    - "websecure"
  routes:
    - kind: "Rule"
      match: "Host(`{{$.Values.ingressroute.host}}`)"
      middlewares:
        - name: "process-exporter-{{$.Values.EnvName}}-basicauth"
      services:
        - name: "metrics"
          port: {{$.Values.service.port}}

{{ end }}


